suppressPackageStartupMessages({
  library(memoise)
  library(jsonlite)
  library(shiny)
  library(scales)
  library(tidyverse)
  library(bslib)
  library(bsicons)
  library(plotly)
  library(leaflet)
  library(readxl)
  library(sf)
  library(stats)
  library(rvest)
  library(httr)
  library(request)
  library(lubridate)
  library(curl)
  library(fs)
  library(svglite)
  library(httr2)
  library(leaflet)
  library(leaflet.extras2)
  library(openrouteservice)
})

add_log("app/utils/core/dependencies.r", "libraries_loaded")
